[package]
name = "topological_sort"
version = "0.1.0"
authors = ["Luz Morales <luzmoralesjimenez@hotmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
